# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/manual/source/conf.py
  
python:
    install:
    - requirements: docs/manual/requirements.txt
