#!/usr/bin/env python

import argparse

argparser = argparse.ArgumentParser ( description = "simple script that fires up an ipython interactive shell with an instantiated browser" )
argparser.add_argument ( "path_to_database" )
args = argparser.parse_args()

import IPython
from smodels.tools import databaseBrowser
from smodels.tools.physicsUnits import fb, pb, GeV, TeV

header = "Welcome to SModelS\n"
header += "browser = Browser ( %s )" % ( args.path_to_database ) 

browser = databaseBrowser.Browser ( args.path_to_database )

IPython.embed ( header=header )
