#!/usr/bin/env python

try:
    import IPython
except ImportError as e:
    print "Ipython is not installed. To use this script, please install ipython."
    import sys
    sys.exit()

import argparse

argparser = argparse.ArgumentParser ( description = "simple script that fires up an ipython interactive shell with an instantiated browser" )
argparser.add_argument ( "path_to_database" )
args = argparser.parse_args()

from smodels.tools import databaseBrowser
from smodels.tools.physicsUnits import fb, pb, GeV, TeV
from smodels.tools import statistics

def getHeader ():
    from smodels.installation import installDirectory
    header = ""
    with open( installDirectory()+"/BANNER") as f:
        lines=f.readlines()
        for line in lines: header+=line

    header += "\n"
    header += "fb, pb, GeV, TeV defined.\n"
    header += "browser = Browser ( '%s' )\n" % ( args.path_to_database ) 
    return header


browser = databaseBrowser.Browser ( args.path_to_database )

IPython.embed ( header=getHeader() )
