name: environment-smodels
channels:
  - conda-forge
dependencies:
  - python==3.10.0
  - pip
  - setuptools
  - wheel
  - pip:
    - matplotlib
    - pandas
    - plotly
    - numpy
    - scipy
    - docutils
    - unum
    - requests
    - pyslha
    - pyhf
    - jsonpatch
    - jsonschema
