name: environment-smodels
channels:
  - conda-forge
dependencies:
  - python
  - pip:
    - matplotlib
    - pandas
    - plotly
    - numpy
    - scipy
    - docutils
    - unum
    - requests
    - pyslha
