all: nllfast12 nllfast21 nllfast31

clean: nllfast12_clean nllfast21_clean nllfast31_clean

nllfast12:
	cd nllfast-1.2 && make
nllfast21:
	cd nllfast-2.1 && make
nllfast31:
	cd nllfast-3.1 && make
nllfast12_clean:
	cd nllfast-1.2 && make clean
nllfast21_clean:
	cd nllfast-2.1 && make clean
nllfast31_clean:
	cd nllfast-3.1 && make clean
