all: pythia6 nllfast
nllfast: nllfast-1.2 nllfast-2.1 nllfast-3.0 nllfast-4.01dcpl nllfast-5.01dcpl
pythia: pythia6

pythia6:
	cd pythia6 && make
nllfast-1.2:
	cd nllfast/nllfast-1.2 && make
nllfast-2.1:
	cd nllfast/nllfast-2.1 && make
nllfast-3.0:
	cd nllfast/nllfast-3.0 && make
nllfast-4.01dcpl:
	cd nllfast/nllfast-4.01dcpl && make
nllfast-5.01dcpl:
	cd nllfast/nllfast-5.01dcpl && make
