#!/usr/bin/python

import sys
file=sys.argv[1]
value=sys.argv[2]

f=open(file)
lines=f.readlines()
f.close()

f=open(file,"write")
for line in lines:
	if "validated" in line:
		f.write ("validated: %s\n" % value )
	else:
		f.write ( line )
