all: nllfast12 nllfast21 nllfast30 nllfast401dcpl nllfast501dcpl

tarballs:
	tar czvf nllfast7.tar.gz nllfast-1.2/
	tar czvf nllfast8.tar.gz nllfast-2.1/

nllfast12:
	cd nllfast-1.2 && make
nllfast21:
	cd nllfast-2.1 && make
nllfast30:
	cd nllfast-3.0 && make
nllfast401dcpl:
	cd nllfast-4.01dcpl && make
nllfast501dcpl:
	cd nllfast-5.01dcpl && make
