name: Debug macOS-14

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v6
# uses: actions/checkout@v7

      - name: Start SSH session
        uses: owenthereal/action-upterm@v1
# uses: mxschmitt/action-tmate@v3
