name: Live macOS-14 Shell (tmate)

on:
  workflow_dispatch:

jobs:
  shell:
    runs-on: macos-14
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
