name: Interactive macOS-26 Shell (upterm)

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: macos-26
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Ensure tmux is working
        run: |
          brew install tmux
          tmux new-session -d -s main
          tmux list-sessions

      - name: Start SSH session
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
