# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SModelS Validation

on:
  push:
    branches: [ master, develop, release/* ]
  pull_request:
    branches: [ master, develop ]
  # Enables manual action execution.
  workflow_dispatch:

jobs:
  test:
    name: OS ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 420

    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
        os: [ubuntu-20.04, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f smodels/share/requirements.txt ]; then python -m pip install -r smodels/share/requirements.txt; fi
        if [ -f test/test_requirements.txt ]; then python -m pip install -r test/test_requirements.txt; fi
        python -m pip install -e .
    - name: Test with unittest
      run: |
        make pythia8
        cd test
        make reduced
